
{% set summary = load_file_data('pyproject.toml') %}

{% set version_match = load_file_regex(
  load_file="VERSION",
  regex_pattern='(.+)') %}
{% set version = version_match[1] %}

package:
  name:  gcdocs
  version: {{  version }}

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python -m pip install . --no-deps -vv
  entry_points:
    - gcdocs = gcdocs.cli:gcdocs
    - datamodel = gcdocs.cli:datamodel


requirements:
  build:
    - python
    - pip
    - setuptools
    - wheel


  run:
    - python
    - jinja2
    - pyyaml
    - click
    - geopandas
    - pandas
    - loguru
    - shapely>=2.0.0
    - babel
    - jsonschema
    - openpyxl
    - ruamel.yaml

  run_constrained:
    - arcpy  # Optional: Only available for users with the ESRI environment set up.
    
    


about:
  summary: "Documentation Generator for Geological 2D Data Model (Geocover)"
  description: "Documentation Generator for Geological 2D Data Model (Geocover)"
  home: https://github.com/swisstopo/lg-geology-data-model
  license: BSD
  dev_url: https://github.com/swisstopo/lg-geology-data-model/src/master/
  doc_url: https://anaconda.org/swisstopo/gcdocs
  doc_source_url: https://raw.githubusercontent.com/swisstopo/lg-geology-data-model/master/README.md


extra:
  recipe-maintainers:
    - ltmom
