
[tool.versioningit.vcs]
# The method key:
method = "git"  # <- The method name

# Parameters to pass to the method:
match = ["*"]
default-tag = "0.0.0"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
