@startuml
skinparam monochrome false
skinparam linetype ortho
skinparam backgroundcolor transparent
skinparam rectangle {{
  roundCorner 50
  BackGroundColor {bg_color}
  LineThickness 10
  LineColor #CEEDDB
}}

skinparam TitlefontColor  {table_color}
skinparam TitleFontSize 50


scale 1

' Color scheme https://colorhunt.co/palette/eaebd0da6c6ccd5656af3e3e
' #EAEBD0 #DA6C6C #CD5656 #AF3E3E


!define table(x) class x << (T,{table_color}) >> {table_bg}
!define view(x) class x << (V,#FFAAAA) >>
!define ent(x) class x << (E,#FFAAAA) >>
!define enum(x) class x << (E,#FFAAAA) >>
!define class(x) class x << (C,{class_color}) >> {class_bg}

!define primary_key(x) <b>PK: x</b>
!define foreign_key(x,reference) <b>FK: </b>x
!define key(x) <b>x</b>
hide methods
hide stereotypes



rectangle   {bg_color};line:{rectangle_color};line.bold; {{
 

title GeoCover 5.0\nMai 2025

{content}

}}

@enduml
