name: Upload artifacts to S3



on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    uses: ./.github/workflows/build.yaml  # use the callable build job to run build
  deploy:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set Package Version
      shell: bash
      run: |
          echo "version=$(<VERSION)" >> $GITHUB_ENV
          echo "=== PKG_VERSION=$version ==="
          echo "RELEASE=$(python -c "import yaml; print(yaml.safe_load(open('datamodel.yaml'))['model']['revision'])")" >> $GITHUB_ENV
          echo "SHORT_RELEASE=$(echo '4.0.0' | cut -d'.' -f1,2)" >> $GITHUB_ENV
          echo "=== RELEASE=${{ env.RELEASE }} ==="
          echo "=== SHORT=${{ env.SHORT_RELEASE }} ==="
    - name: Download assets from build
      uses: actions/download-artifact@v4
      with:
          name: geology-data-model-${{ env.RELEASE }}
    - name: Upload folder to bucket
      uses: a-sync/s3-uploader@master
      with:
        args: --recursive --exclude "*.log"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'eu-central-1'
        S3_BUCKET: ${{ secrets.AWS_BUCKET }}
        S3_KEY: datamodel/${{ env.SHORT_RELEASE }}
        FILE: './outputs'

