name: Build conda and pip packages


on:
  workflow_call:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - master
      - develop
      - 'releases/**'


jobs:
  build-markdown:
    name: Build on ${{ matrix.python-version }} and  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.12' ]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,default
          channel-priority: true
          activate-environment: DATAMODEL
          environment-file: environment.yaml

      - name: conda install
        shell: bash -el {0}
        run: $CONDA/bin/conda install conda-build anaconda-client -y

      - name: Check conda installation
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: conda build
        shell: bash -el {0}
        run: |
          $CONDA/bin/conda build  --python ${{ matrix.python-version }} --output-folder  ./conda-out/  recipe
    

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conda-package-${{ matrix.python-version }}-${{ matrix.python-version }}
          path: |
            conda-out/noarch/geocover*.tar.bz2


