name: Build conda and pip packages


on:
  workflow_call:
  push:
    branches:
      - master
      - 'releases/**'
  pull_request:
    branches:
      - master
      - develop
      - 'releases/**'


jobs:
  build-markdown:
    name: Build on ${{ matrix.python-version }} and  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # Don't cancel other jobs if one fails
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        python-version: [ '3.12' ]
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true
          activate-environment: DATAMODEL
          conda-solver: classic

      - name: Conda install and update
        shell: bash -el {0}
        run: |
            conda install conda-build anaconda-client -y
            conda update conda
           
            
      - name: Conda dependencies
        shell: bash -el {0}
        run: |
            conda install -y -c conda-forge  jinja2 pyyaml click geopandas pandas click loguru shapely babel jsonschema openpyxl ruamel.yaml

      - name: Check conda installation
        shell: bash -el {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort

      - name: Conda build
        shell: bash -el {0}
        run: |
          conda build  --python ${{ matrix.python-version }} --output-folder  ./conda-out/  recipe
    

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: conda-package-${{ matrix.os }}-${{ matrix.python-version }}
          path: |
            conda-out/*/geocover*


