name: Uploading assets to GitHub release


on:
  push:
    tags:
      - "v*.*.*"



jobs:
  build:
    uses: ./.github/workflows/build.yaml  # use the callable build job to run build
  release:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    steps:
      - name: Download assets from build
        uses: actions/download-artifact@v4
        with:
          name: document-artifacts
      - name: Release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            outputs/de/datamodel.pdf
            outputs/fr/datamodel.pdf
            outputs/de/datamodel.docx
            outputs/fr/datamodel.docx
            outputs/ER-GCOVER.svg
            outputs/ER-GCOVER.pdf
            exports/coded_domains.xlsx
            exports/all_geolcode.xlsx
            exports/geocover-schema-sde.json
            outputs/geocover-schema-sde.png
            outputs/geocover-schema-sde.svg

