name: Uploading assets to GitHub release


on:
  push:
    tags:
      - "v*.*.*"



jobs:
  build:
    uses: ./.github/workflows/build.yaml  # use the callable build job to run build
  release:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    permissions:
      contents: write # Grant write permission for creating releases and uploading assets
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set releases variables
        shell: bash
        run: |
          RELEASE=$(python -c "import yaml; print(yaml.safe_load(open('datamodel.yaml'))['model']['revision'])")
          SOURCES_DIR=$(python -c "import yaml; print(yaml.safe_load(open('datamodel.yaml'))['model']['sources_dir'])")
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "SOURCES_DIR=$SOURCES_DIR" >> $GITHUB_ENV
          echo "SHORT_RELEASE=$(echo $RELEASE | cut -d'.' -f1,2)" >> $GITHUB_ENV
          echo "version=$(<VERSION)" >> $GITHUB_ENV
      - name: Print release variables
        shell: bash
        run: |
          echo "=== PKG_VERSION=${{ env.version }} ==="
          echo "=== RELEASE=${{ env.RELEASE }} ==="
          echo "=== SHORT=${{ env.SHORT_RELEASE }} ==="
          echo "=== SOURCES_DIR=${{ env.SOURCES_DIR }} ==="
      - name: Download assets from build
        uses: actions/download-artifact@v4
        with:
          name: geology-data-model-${{ env.RELEASE }}
          path: ./temp-artifacts

      - name: Rename files to avoid conflicts
        run: |
          mkdir -p release-assets
          # Copy with language-specific names
          cp temp-artifacts/outputs/de/datamodel.pdf release-assets/datamodel-de.pdf
          cp temp-artifacts/outputs/fr/datamodel.pdf release-assets/datamodel-fr.pdf
          cp temp-artifacts/outputs/de/datamodel.docx release-assets/datamodel-de.docx
          cp temp-artifacts/outputs/fr/datamodel.docx release-assets/datamodel-fr.docx
          cp temp-artifacts/outputs/ER-GCOVER.svg release-assets/ER-GCOVER.svg
          cp temp-artifacts/outputs/ER-GCOVER.pdf release-assets/ER-GCOVER.pdf
          cp temp-artifacts/${{ env.SOURCES_DIR }}/gcoverp_export_simple.json release-assets/gcoverp_export_simple.json
          # List files to verify
          ls -la release-assets/
      - name: Ensure file handles are properly closed
        run: |
           # Ensure all files are properly closed before upload
           for file in release-assets/*; do
              exec 3<>"$file"
              exec 3>&-
           done
      - name: Get tag name
        id: get_tag
        run: echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          # Step 3: Create GitHub Release and upload artifacts using ncipollo/release-action
      - name: Create GitHub Release
        # Use the ncipollo/release-action. It's good practice to pin to a specific version.
        uses: ncipollo/release-action@v1.16.0

        # Define inputs for the action using the 'with' keyword
        with:
                 token: ${{ secrets.TOKEN }}
                 tag: ${{ github.ref_name }} # github.ref_name directly gives the tag name (e.g., v1.0.0)
                 name: Release ${{ github.ref_name }}

                 # Optional: The body/description of the release notes.
                 # You can include dynamic content, commit messages, or static text.
                 # Here, we're using a multiline string for readability.
                 body: |
                   ## Release Notes for ${{ github.ref_name }}
                   
                   This is an automated release.
                   
                 draft: false
                 prerelease: false
                 artifacts: |
                   release-assets/*
             

      - name: Upload Release Assets using gh CLI
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          # The tag name from the release event or extracted from GITHUB_REF
          RELEASE_TAG="${{ steps.get_tag.outputs.TAG }}"

          # Upload each file individually
          gh release upload "$RELEASE_TAG" release-assets/datamodel-de.pdf --clobber
          gh release upload "$RELEASE_TAG" release-assets/datamodel-fr.pdf --clobber
          gh release upload "$RELEASE_TAG" release-assets/datamodel-de.docx --clobber
          gh release upload "$RELEASE_TAG" release-assets/datamodel-fr.docx --clobber
          gh release upload "$RELEASE_TAG" release-assets/ER-GCOVER.svg --clobber
          gh release upload "$RELEASE_TAG" release-assets/ER-GCOVER.pdf --clobber
          gh release upload "$RELEASE_TAG" release-assets/gcoverp_export_simple.json --clobber




