name: Uploading assets to GitHub release


on:
  push:
    tags:
      - "v*.*.*"



jobs:
  build:
    uses: ./.github/workflows/build.yaml  # use the callable build job to run build
  release:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set releases variables
        shell: bash
        run: |
          RELEASE=$(python -c "import yaml; print(yaml.safe_load(open('datamodel.yaml'))['model']['revision'])")
          SOURCES_DIR=$(python -c "import yaml; print(yaml.safe_load(open('datamodel.yaml'))['model']['sources_dir'])")
          echo "RELEASE=$RELEASE" >> $GITHUB_ENV
          echo "SOURCES_DIR=$SOURCES_DIR" >> $GITHUB_ENV
          echo "SHORT_RELEASE=$(echo $RELEASE | cut -d'.' -f1,2)" >> $GITHUB_ENV
          echo "version=$(<VERSION)" >> $GITHUB_ENV
      - name: Print release variables
        shell: bash
        run: |
          echo "=== PKG_VERSION=${{ env.version }} ==="
          echo "=== RELEASE=${{ env.RELEASE }} ==="
          echo "=== SHORT=${{ env.SHORT_RELEASE }} ==="
          echo "=== SOURCES_DIR=${{ env.SOURCES_DIR }} ==="
      - name: Download assets from build
        uses: actions/download-artifact@v4
        with:
          name: geology-data-model-${{ env.RELEASE }}
          path: ./temp-artifacts

      - name: Rename files to avoid conflicts
        run: |
          mkdir -p release-assets
          # Copy with language-specific names
          cp temp-artifacts/outputs/de/datamodel.pdf release-assets/datamodel-de.pdf
          cp temp-artifacts/outputs/fr/datamodel.pdf release-assets/datamodel-fr.pdf
          cp temp-artifacts/outputs/de/datamodel.docx release-assets/datamodel-de.docx
          cp temp-artifacts/outputs/fr/datamodel.docx release-assets/datamodel-fr.docx
          cp temp-artifacts/outputs/ER-GCOVER.svg release-assets/ER-GCOVER.svg
          cp temp-artifacts/outputs/ER-GCOVER.pdf release-assets/ER-GCOVER.pdf
          cp temp-artifacts/${{ env.SOURCES_DIR }}/gcoverp_export_simple.json release-assets/gcoverp_export_simple.json
          # List files to verify
          ls -la release-assets/
      - name: Ensure file handles are properly closed
        run: |
           # Ensure all files are properly closed before upload
           find release-assets -type f -exec bash -c 'exec 3<>"{}"' \;

      - name: Release assets (batch 1)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            release-assets/datamodel-de.pdf
            release-assets/datamodel-fr.pdf
            release-assets/datamodel-de.docx
            release-assets/datamodel-fr.docx

      - name: Release assets (batch 2)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
             release-assets/ER-GCOVER.svg
             release-assets/ER-GCOVER.pdf
             release-assets/gcoverp_export_simple.json


